export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const PRODUCTS_DOWNLOAD_SUCCESS = 'START_PRODUCTS_DOWNLOAD_SUCCESS';
export const PRODUCTS_DOWNLOAD_ERROR = 'START_PRODUCTS_DOWNLOAD_ERROR';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const PRODUCT_DELETED_SUCCESS = 'PRODUCT_DELETED_SUCCESS';
export const PRODUCT_DELETED_ERROR = 'PRODUCT_DELETED_ERROR';

export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';
export const START_PRODUCT_EDIT = 'START_PRODUCT_EDIT';
export const PRODUCT_EDITED_SUCCESS = 'PRODUCT_EDITED_SUCCESS';
export const PRODUCT_EDITED_ERROR = 'PRODUCT_EDITED_ERROR';